apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: manoranjaniy/to-do-app:v2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-srv-cluster
spec:
  type: ClusterIP
  selector:
    app: to-do-app
  ports:
    - name: to-do-app-srv-cluster-ip
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: to-do-app-lb-srv
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: to-do-app
  type: LoadBalancer



